### PR TITLE
IE11 Fix

### PR DESCRIPTION
**Pull request by waynebrantley**
Fix IE11 invalid calling object as detailed here:
https://github.com/localForage/localForage-observable/issues/22

### CODE REVIEW

**Review by tofumatt — APPROVED** [review]
As mentioned in #22, these types seem pretty out-of-date.

But the fix here works, so approved and I'll get a new release out soon.

**Comment by tofumatt** [comment]
Actually, looks like this repo isn't hooked up to CI like the main one.

That's something I should take care of eventually, but for now: could you bump the version number and ship a new release, @thgreasi?

**Comment by waynebrantley** [comment]
@tofumatt @thgreasi Would it be possible to ship the new release?

**Comment by tofumatt** [comment]
Unfortunately it looks like the permissions on a lot of the localForage npm modules aren't as well-organised as they should be. 😓

I'll ping @thgreasi and ask him to update the npm module, but for now you can at least install it via git with:

```bash
npm install --save localForage/localForage-observable
```

Sorry about the delay!

**Comment by waynebrantley** [comment]
Oh, I did realize that...ok..thx.

**Comment by tofumatt** [comment]
Just an update: we sorted out access and 2.0.1 has been published to npm. Thanks for your PR and your patience @waynebrantley! 😄

**Pull request merged**
